### ISSUE TITLE
[Feature Request]存档视频评论

### ISSUE THREAD

**Issue by MiAcStudio** [saveweb/biliarchiver#10]

**Comment by yzqzss** [comment]
之前 `/x/web-interface/view/detail` 这个 API（`biliarchiver` 的 `info.json` 就是来自这个 API）会返回三个热门评论，但是最近叔叔这个 API 连三个热门评论都不输出了。  

看之后是把 `/x/v2/reply` 这个 API 的内容嵌入到 `info.json` 里，还是给评论单独存个 json 文件。

**Comment by yzqzss** [comment]
0.1.7 中已实现。
（只存 20 个热门评论）

**Comment by MiAcStudio** [comment]
I highly appreciate it.
