### ISSUE TITLE
`.DS_Store` being renamed

### ISSUE THREAD

**Issue by OverflowCat** [saveweb/biliarchiver#12]
逆天

<img width="977" alt="image" src="https://github.com/saveweb/biliarchiver/assets/20166026/a7091a8f-1365-45d5-b162-0b789e729baa">

![](https://github.com/saveweb/biliarchiver/assets/20166026/b00731f1-398d-4b77-b225-f191112209f3)

**Comment by yzqzss** [comment]
逆天，这不科学。
你用 mac 你来修。😇

**Comment by OverflowCat** [comment]
真的有人还在用旧版并且直接从以前的版本安装最新的？直接把这段代码删了吧…

yzqzss ***@***.***> 于 2023年11月5日周日 20:11写道：

**Comment by yzqzss** [comment]
吼啊！

**Comment by yzqzss** [comment]
但是我还是不理解为什么路径都对不上，是怎么 .exists() == True 的……
